package com.pfms.dao.mybatis.dao;

import com.pfms.dao.mybatis.model.PfmsSys;
import com.pfms.dao.mybatis.model.PfmsSysExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PfmsSysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_sys
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int countByExample(PfmsSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_sys
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int deleteByExample(PfmsSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_sys
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int deleteByPrimaryKey(String sysId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_sys
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int insert(PfmsSys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_sys
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int insertSelective(PfmsSys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_sys
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    List<PfmsSys> selectByExample(PfmsSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_sys
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    PfmsSys selectByPrimaryKey(String sysId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_sys
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int updateByExampleSelective(@Param("record") PfmsSys record, @Param("example") PfmsSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_sys
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int updateByExample(@Param("record") PfmsSys record, @Param("example") PfmsSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_sys
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int updateByPrimaryKeySelective(PfmsSys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_sys
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int updateByPrimaryKey(PfmsSys record);
}