package com.pfms.dao.mybatis.dao;

import com.pfms.dao.mybatis.model.PfmsUsageOne;
import com.pfms.dao.mybatis.model.PfmsUsageOneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PfmsUsageOneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage1
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int countByExample(PfmsUsageOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage1
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int deleteByExample(PfmsUsageOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage1
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage1
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int insert(PfmsUsageOne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage1
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int insertSelective(PfmsUsageOne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage1
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    List<PfmsUsageOne> selectByExample(PfmsUsageOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage1
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    PfmsUsageOne selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage1
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int updateByExampleSelective(@Param("record") PfmsUsageOne record, @Param("example") PfmsUsageOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage1
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int updateByExample(@Param("record") PfmsUsageOne record, @Param("example") PfmsUsageOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage1
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int updateByPrimaryKeySelective(PfmsUsageOne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_usage1
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int updateByPrimaryKey(PfmsUsageOne record);
}