package com.pfms.dao.mybatis.dao;

import com.pfms.dao.mybatis.model.PfmsUser;
import com.pfms.dao.mybatis.model.PfmsUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PfmsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_user
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int countByExample(PfmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_user
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int deleteByExample(PfmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_user
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_user
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int insert(PfmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_user
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int insertSelective(PfmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_user
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    List<PfmsUser> selectByExample(PfmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_user
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    PfmsUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_user
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int updateByExampleSelective(@Param("record") PfmsUser record, @Param("example") PfmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_user
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int updateByExample(@Param("record") PfmsUser record, @Param("example") PfmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_user
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int updateByPrimaryKeySelective(PfmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_user
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    int updateByPrimaryKey(PfmsUser record);
}