package com.pfms.dao.mybatis.model;

import java.util.Date;

public class PfmsUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_user.ID
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_user.LOGIN_NAME
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_user.PASSWORD
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_user.NAME
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_user.FIRST_LOGIN
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private String firstLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_user.GENDER
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_user.BIRTH_DATE
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private Date birthDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_user.MAIL_ADDRESS
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private String mailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_user.USER_TYPE
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_user.TIMESTAMP
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private Date timestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_user.USAGE_NUM
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private Integer usageNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_user.ID
     *
     * @return the value of pfmsdb_user.ID
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_user.ID
     *
     * @param id the value for pfmsdb_user.ID
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_user.LOGIN_NAME
     *
     * @return the value of pfmsdb_user.LOGIN_NAME
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_user.LOGIN_NAME
     *
     * @param loginName the value for pfmsdb_user.LOGIN_NAME
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_user.PASSWORD
     *
     * @return the value of pfmsdb_user.PASSWORD
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_user.PASSWORD
     *
     * @param password the value for pfmsdb_user.PASSWORD
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_user.NAME
     *
     * @return the value of pfmsdb_user.NAME
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_user.NAME
     *
     * @param name the value for pfmsdb_user.NAME
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_user.FIRST_LOGIN
     *
     * @return the value of pfmsdb_user.FIRST_LOGIN
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public String getFirstLogin() {
        return firstLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_user.FIRST_LOGIN
     *
     * @param firstLogin the value for pfmsdb_user.FIRST_LOGIN
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setFirstLogin(String firstLogin) {
        this.firstLogin = firstLogin == null ? null : firstLogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_user.GENDER
     *
     * @return the value of pfmsdb_user.GENDER
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_user.GENDER
     *
     * @param gender the value for pfmsdb_user.GENDER
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_user.BIRTH_DATE
     *
     * @return the value of pfmsdb_user.BIRTH_DATE
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_user.BIRTH_DATE
     *
     * @param birthDate the value for pfmsdb_user.BIRTH_DATE
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_user.MAIL_ADDRESS
     *
     * @return the value of pfmsdb_user.MAIL_ADDRESS
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public String getMailAddress() {
        return mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_user.MAIL_ADDRESS
     *
     * @param mailAddress the value for pfmsdb_user.MAIL_ADDRESS
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress == null ? null : mailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_user.USER_TYPE
     *
     * @return the value of pfmsdb_user.USER_TYPE
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_user.USER_TYPE
     *
     * @param userType the value for pfmsdb_user.USER_TYPE
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_user.TIMESTAMP
     *
     * @return the value of pfmsdb_user.TIMESTAMP
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_user.TIMESTAMP
     *
     * @param timestamp the value for pfmsdb_user.TIMESTAMP
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_user.USAGE_NUM
     *
     * @return the value of pfmsdb_user.USAGE_NUM
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public Integer getUsageNum() {
        return usageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_user.USAGE_NUM
     *
     * @param usageNum the value for pfmsdb_user.USAGE_NUM
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setUsageNum(Integer usageNum) {
        this.usageNum = usageNum;
    }
}