package com.pfms.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class PfmsUsageOne {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage1.ID
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage1.TYPE
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage1.NAME
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage1.AMOUNT
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage1.CHILDREN
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private Integer children;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage1.CREATOR_ID
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage1.CREATE_TIME
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage1.DESCRIPT
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private String descript;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage1.MONTHBUDGET
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private BigDecimal monthbudget;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage1.ID
     *
     * @return the value of pfmsdb_usage1.ID
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage1.ID
     *
     * @param id the value for pfmsdb_usage1.ID
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage1.TYPE
     *
     * @return the value of pfmsdb_usage1.TYPE
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage1.TYPE
     *
     * @param type the value for pfmsdb_usage1.TYPE
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage1.NAME
     *
     * @return the value of pfmsdb_usage1.NAME
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage1.NAME
     *
     * @param name the value for pfmsdb_usage1.NAME
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage1.AMOUNT
     *
     * @return the value of pfmsdb_usage1.AMOUNT
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage1.AMOUNT
     *
     * @param amount the value for pfmsdb_usage1.AMOUNT
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage1.CHILDREN
     *
     * @return the value of pfmsdb_usage1.CHILDREN
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public Integer getChildren() {
        return children;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage1.CHILDREN
     *
     * @param children the value for pfmsdb_usage1.CHILDREN
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setChildren(Integer children) {
        this.children = children;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage1.CREATOR_ID
     *
     * @return the value of pfmsdb_usage1.CREATOR_ID
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage1.CREATOR_ID
     *
     * @param creatorId the value for pfmsdb_usage1.CREATOR_ID
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage1.CREATE_TIME
     *
     * @return the value of pfmsdb_usage1.CREATE_TIME
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage1.CREATE_TIME
     *
     * @param createTime the value for pfmsdb_usage1.CREATE_TIME
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage1.DESCRIPT
     *
     * @return the value of pfmsdb_usage1.DESCRIPT
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public String getDescript() {
        return descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage1.DESCRIPT
     *
     * @param descript the value for pfmsdb_usage1.DESCRIPT
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setDescript(String descript) {
        this.descript = descript == null ? null : descript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage1.MONTHBUDGET
     *
     * @return the value of pfmsdb_usage1.MONTHBUDGET
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public BigDecimal getMonthbudget() {
        return monthbudget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage1.MONTHBUDGET
     *
     * @param monthbudget the value for pfmsdb_usage1.MONTHBUDGET
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setMonthbudget(BigDecimal monthbudget) {
        this.monthbudget = monthbudget;
    }
}