package com.pfms.dao.mybatis.model;

import java.math.BigDecimal;

public class ProsetVm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsvm_proset.ID
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsvm_proset.MONTH
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private String month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsvm_proset.NAME
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsvm_proset.TYPE
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsvm_proset.MONTHBUDGET
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private BigDecimal monthbudget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsvm_proset.REALAMOUNT
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private BigDecimal realamount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsvm_proset.ID
     *
     * @return the value of pfmsvm_proset.ID
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsvm_proset.ID
     *
     * @param id the value for pfmsvm_proset.ID
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsvm_proset.MONTH
     *
     * @return the value of pfmsvm_proset.MONTH
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsvm_proset.MONTH
     *
     * @param month the value for pfmsvm_proset.MONTH
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsvm_proset.NAME
     *
     * @return the value of pfmsvm_proset.NAME
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsvm_proset.NAME
     *
     * @param name the value for pfmsvm_proset.NAME
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsvm_proset.TYPE
     *
     * @return the value of pfmsvm_proset.TYPE
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsvm_proset.TYPE
     *
     * @param type the value for pfmsvm_proset.TYPE
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsvm_proset.MONTHBUDGET
     *
     * @return the value of pfmsvm_proset.MONTHBUDGET
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public BigDecimal getMonthbudget() {
        return monthbudget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsvm_proset.MONTHBUDGET
     *
     * @param monthbudget the value for pfmsvm_proset.MONTHBUDGET
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setMonthbudget(BigDecimal monthbudget) {
        this.monthbudget = monthbudget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsvm_proset.REALAMOUNT
     *
     * @return the value of pfmsvm_proset.REALAMOUNT
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public BigDecimal getRealamount() {
        return realamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsvm_proset.REALAMOUNT
     *
     * @param realamount the value for pfmsvm_proset.REALAMOUNT
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setRealamount(BigDecimal realamount) {
        this.realamount = realamount;
    }
}