package com.pfms.dao.mybatis.model;

import java.math.BigDecimal;

public class RealStatistics extends RealStatisticsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_realStatistics.BUDGET
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private BigDecimal budget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_realStatistics.REALAMOUNT
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private BigDecimal realamount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_realStatistics.BUDGET
     *
     * @return the value of pfmsdb_realStatistics.BUDGET
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public BigDecimal getBudget() {
        return budget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_realStatistics.BUDGET
     *
     * @param budget the value for pfmsdb_realStatistics.BUDGET
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setBudget(BigDecimal budget) {
        this.budget = budget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_realStatistics.REALAMOUNT
     *
     * @return the value of pfmsdb_realStatistics.REALAMOUNT
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public BigDecimal getRealamount() {
        return realamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_realStatistics.REALAMOUNT
     *
     * @param realamount the value for pfmsdb_realStatistics.REALAMOUNT
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setRealamount(BigDecimal realamount) {
        this.realamount = realamount;
    }
}