package com.pfms.dao.mybatis.model;

public class SequenceKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.SEQ_NAME
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private String seqName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.DATE
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private String date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.SEQ_NAME
     *
     * @return the value of sequence.SEQ_NAME
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public String getSeqName() {
        return seqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.SEQ_NAME
     *
     * @param seqName the value for sequence.SEQ_NAME
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setSeqName(String seqName) {
        this.seqName = seqName == null ? null : seqName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.DATE
     *
     * @return the value of sequence.DATE
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.DATE
     *
     * @param date the value for sequence.DATE
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }
}