package com.pfms.dao.mybatis.model;

public class Sequence extends SequenceKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.CURRENT_VAL
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private Integer currentVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.INCREMENT_VAL
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    private Integer incrementVal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.CURRENT_VAL
     *
     * @return the value of sequence.CURRENT_VAL
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public Integer getCurrentVal() {
        return currentVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.CURRENT_VAL
     *
     * @param currentVal the value for sequence.CURRENT_VAL
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setCurrentVal(Integer currentVal) {
        this.currentVal = currentVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.INCREMENT_VAL
     *
     * @return the value of sequence.INCREMENT_VAL
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public Integer getIncrementVal() {
        return incrementVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.INCREMENT_VAL
     *
     * @param incrementVal the value for sequence.INCREMENT_VAL
     *
     * @mbggenerated Sun May 22 17:23:06 CST 2016
     */
    public void setIncrementVal(Integer incrementVal) {
        this.incrementVal = incrementVal;
    }
}